image: Ubuntu  

stack: jdk 11  


branches:
  only:
    - main 

build: off  

cmd: 
  - mysqld &


build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true

install:
  
- java -jar ./artifacts/aqa-shop.jar &