image: Ubuntu  

stack: jdk 11  

services: 

  - mysql

branches:
  only:
    - main 

build: off  

install:
  
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true