image: Ubuntu  

stack: jdk 11  


branches:
  only:
    - main 

build: off  


build_script:
  - docker-compose up -d
  - timeout /t 10
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true

install:
  
- java -jar ./artifacts/aqa-shop.jar &