image: Ubuntu  

stack: jdk 11  


branches:
  only:
    - main 

build: off  

before_build:
  - docker-compose up --build -d


build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true

after_test:
  - docker-compose down

install:

- docker-compose up -d
- sleep 60  
- java -jar ./artifacts/aqa-shop.jar &